# Generated by Django 5.2.11 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(max_length=120)),
                ('meta_description', models.CharField(max_length=180)),
                ('github_username', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
