# Generated by Django 5.2.11 on 2026-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='click_sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='click_sound_volume',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='empty_click_sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='empty_click_sound_volume',
            field=models.FloatField(default=0.3),
        ),
    ]
