# Generated by Django 5.2.11 on 2026-02-22 17:49

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_sitesetting_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='click_sound',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='sounds/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='empty_click_sound',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='sounds/'),
        ),
    ]
