# Generated by Django 5.2.7 on 2026-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_sitesetting_click_sound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='sounds_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
