# Generated by Django 5.2.11 on 2026-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sounds_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, default='info@hijbullah.me', max_length=254),
        ),
    ]
