# Generated by Django 5.2.11 on 2026-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True),
        ),
    ]
