# Generated by Django 5.2.11 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('abstract', models.TextField()),
                ('methodology', models.TextField()),
                ('technologies', models.TextField()),
                ('paper_link', models.URLField(blank=True)),
                ('pdf_upload', models.FileField(blank=True, null=True, upload_to='research/papers/')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('published', 'Published')], default='planning', max_length=20)),
                ('future_scope', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
