# Generated by Django 5.2.7 on 2026-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='contributors',
            field=models.CharField(blank=True, help_text='Comma-separated list of contributors', max_length=500),
        ),
    ]
