# Generated by Django 5.2.7 on 2026-02-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_research_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='methodology',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='technologies',
            field=models.TextField(blank=True),
        ),
    ]
