# Generated by Django 5.2.7 on 2026-02-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_research_abstract_alter_research_methodology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_requests', to='research.research')),
            ],
            options={
                'verbose_name': 'Research Contribution Request',
                'verbose_name_plural': 'Research Contribution Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
