# Generated by Django 5.2.11 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=255)),
                ('short_bio', models.TextField()),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='hero/resume/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='hero/profile/')),
                ('background_type', models.CharField(choices=[('gradient', 'Gradient'), ('image', 'Image'), ('video', 'Video')], default='gradient', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
