# Generated by Django 5.2.11 on 2026-02-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='background_type',
            field=models.CharField(choices=[('gradient', 'Gradient'), ('particles', 'Particles'), ('solid', 'Solid Color'), ('image', 'Image'), ('video', 'Video')], default='gradient', max_length=20),
        ),
    ]
