# Generated by Django 5.2.11 on 2026-03-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_hero_background_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='resume_file',
        ),
    ]
