# Generated by Django 5.2.11 on 2026-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('link', models.CharField(help_text='URL or mailto: or tel:', max_length=300)),
                ('icon_type', models.CharField(choices=[('gmail', 'Gmail'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('website', 'Website'), ('custom', 'Custom (use image only)')], default='custom', max_length=20)),
                ('color_from', models.CharField(default='cyan-500', help_text='Tailwind color e.g. cyan-500', max_length=40)),
                ('color_to', models.CharField(default='emerald-500', help_text='Tailwind color e.g. emerald-500', max_length=40)),
                ('profile_image_url', models.URLField(blank=True, help_text='Background watermark image URL')),
                ('image_opacity', models.FloatField(default=0.2, help_text='Watermark opacity 0.0 – 1.0')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Profile',
                'verbose_name_plural': 'Contact Profiles',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
