# Generated by Django 5.2.11 on 2026-02-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprofile',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Background watermark image', null=True, upload_to='contact_profiles/'),
        ),
    ]
