# Generated by Django 5.2.11 on 2026-02-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_feedback_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower = shown first in public card deck'),
        ),
    ]
