# Generated by Django 5.2.7 on 2026-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_feedback_options_feedback_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
