# Generated by Django 5.2.11 on 2026-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_add_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Admin reply to this feedback', null=True),
        ),
    ]
