# Generated by Django 4.2.30 on 2026-10-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_feedback_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='admin_reply',
            field=models.TextField(blank=True, default='', help_text='Sent reply to sender'),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
