# Generated by Django 4.2.30 on 2026-09-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_page_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
