# Generated by Django 5.2.11 on 2026-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('work_details', models.TextField(help_text='Describe the work / project requirements')),
                ('proposed_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_type', models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('task', 'Per Task / Fixed'), ('monthly', 'Per Month')], default='hourly', max_length=20)),
                ('duration', models.CharField(help_text='e.g. 2 weeks, 1 month, ongoing', max_length=120)),
                ('message', models.TextField(blank=True, help_text='Additional notes or context')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Hire Request',
                'verbose_name_plural': 'Hire Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
