# Generated by Django 5.2.11 on 2026-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailab',
            name='details',
            field=models.TextField(blank=True, help_text='Project description and details'),
        ),
        migrations.AddField(
            model_name='ailab',
            name='link',
            field=models.URLField(blank=True, help_text='Link to project/paper/demo', max_length=500),
        ),
        migrations.AddField(
            model_name='ailab',
            name='title',
            field=models.CharField(default='Untitled Project', help_text='Project/Experiment Title', max_length=220),
        ),
        migrations.AlterField(
            model_name='ailab',
            name='dataset_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='ailab',
            name='experiment_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='ailab',
            name='model_name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
