# Generated by Django 5.2.11 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=160)),
                ('date', models.DateField()),
                ('certificate_link', models.URLField(blank=True)),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='achievements/badges/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
