# Generated by Django 5.2.11 on 2026-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='certificate_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='issuer',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
