# Generated by Django 5.2.11 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='experience/logos/')),
                ('highlight', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-highlight', '-created_at'],
            },
        ),
    ]
