# Generated by Django 4.2.30 on 2026-09-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['display_order', '-highlight', '-created_at']},
        ),
        migrations.AddField(
            model_name='experience',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
