# Generated by Django 5.2.11 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('AI', 'AI'), ('Web', 'Web'), ('IoT', 'IoT'), ('Tools', 'Tools')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=50)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
