# Generated by Django 5.2.7 on 2026-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('AI/ML', 'AI/ML'), ('Web', 'Web'), ('IoT', 'IoT'), ('Tools', 'Tools')], max_length=50),
        ),
    ]
