# Generated by Django 5.2.11 on 2026-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('board', 'Board'), ('university', 'University'), ('school', 'School'), ('madrasha', 'Madrasha'), ('college', 'College')], default='university', max_length=20)),
                ('passing_year', models.CharField(help_text='e.g. 2024 or 2026 (Expected)', max_length=50)),
                ('result', models.CharField(blank=True, help_text='e.g. GPA 5.0, CGPA 4.0', max_length=50, null=True)),
                ('institution_logo', models.ImageField(blank=True, help_text='Optional logo', null=True, upload_to='education/logos/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['display_order', '-passing_year'],
            },
        ),
    ]
