# Generated by Django 5.2.11 on 2026-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Currently studying here'),
        ),
    ]
