# Generated by Django 5.2.11 on 2026-03-12 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_education_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['display_order', '-end_date'], 'verbose_name_plural': 'Education'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='passing_year',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected graduation date if current', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_type',
            field=models.CharField(choices=[('board', 'Board'), ('university', 'University'), ('school', 'School'), ('madrasah', 'Madrasah'), ('college', 'College')], default='university', max_length=20),
        ),
    ]
