# Generated by Django 5.2.11 on 2026-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, help_text='Certificate (PDF or Image)', null=True, upload_to='education/certificates/'),
        ),
    ]
