# Generated by Django 5.2.11 on 2026-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_education_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Dhaka, Bangladesh', max_length=255, null=True),
        ),
    ]
